### PR TITLE
feat: upgrade to vp2

### PR DESCRIPTION
**Pull request by Mister-Hope**
Hi there, this is Mr.hope from [vuepress team](https://github.com/vuepress), just have some spare time upgrading this awesome doc to VuePress2. VP2 has better performance.

The mirror docs works fine on my machine. But I am afraid that since VuePress2 is using Vue3, so the ad component probably cannot work without an upgrade. So this PR is dropping it temporarily. If you like this PR, you can update the Ad components yourself and feel free to call me if you have troubles.

### CODE REVIEW

**Comment by insistcp** [comment]
您的邮件已安全到达目的地！
                  谢谢  陈鹏

**Comment by WaterAndBread** [comment]
谢谢，您的邮件已收到。祝您天天快乐！

**Comment by visionguo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Mister-Hope** [comment]
Hi there, do you need me edit this PR?

**Pull request closed without merging**
