### PR TITLE
fix:local_repo.md

### PR DESCRIPTION
**Pull request by rockcitystore**
wrong path #134

### CODE REVIEW

**Comment by twang2218** [comment]
@rockcitystore 不仅仅是这一个路径的问题，前面也有 `/tmp/registry`，而且这篇文字的上下文都是介绍 docker registry v1 的，仅改变链接有些功能依旧可能不正常，需要改写为针对 docker registry v2 的介绍。

建议参考官方文档：

* <https://docs.docker.com/registry/deploying/>
* <https://docs.docker.com/registry/configuration/>
* <https://docs.docker.com/registry/recipes/nginx/>

**Comment by yeasy** [comment]
@rockcitystore Do you prefer I merge this patch first or wait you to refine with all the updates?
Thanks!

**Comment by rockcitystore** [comment]
@yeasy sry i prefer leave this issue here and wait for guys done all updates

**Comment by twang2218** [comment]
@rockcitystore Don't be sorry, it's ok. I will update the chapter after I finished the container chapter. Thank you for raising the issue. 

And for now, I think just close this pull request, and leave the issue open until the registry chapter has been updated.

**Pull request merged**
